### ISSUE TITLE
Issue when custom map to @

### ISSUE THREAD

**Issue by svermeulen** [wincent/replay#4]
https://github.com/wincent/replay/blob/3c47553ead27a3f08826c9e0a9d073b36494104d/autoload/replay.vim#L47

Shouldn't this be `normal! @@` to avoid the case where someone has @ mapped to something else?

**Comment by wincent** [comment]
Ah yes, I think you're right. I'm already dealing with that in the `feedkeys()` calls by passing "n", but we probably want `normal!` as well.

Out of curiosity, what do you have "@" mapped to, if anything?
